// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7687c7b9-4141-4b3b-ba7e-2312f1eb028b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPCSwitchIOTChange();
void onColorIOTChange();

bool pC_StatusIOT;
float temperaturIOT;
CloudColor colorIOT;
bool pC_SwitchIOT;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pC_StatusIOT, READ, ON_CHANGE, NULL, 60);
  ArduinoCloud.addProperty(temperaturIOT, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(colorIOT, READWRITE, ON_CHANGE, onColorIOTChange);
  ArduinoCloud.addProperty(pC_SwitchIOT, READWRITE, ON_CHANGE, onPCSwitchIOTChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
